package kotlinx.serialization;

import java.util.List;
import kotlin.Deprecated;
import kotlin.DeprecationLevel;
import kotlin.Metadata;
import kotlin.ReplaceWith;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;

/* JADX INFO: compiled from: SerializationExceptions.kt */
/* JADX INFO: loaded from: classes7.dex */
@Metadata(d1 = {"\u0000\u001e\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\u0003\n\u0000\n\u0002\u0010 \n\u0002\b\u0010\b\u0007\u0018\u00002\u00020\u0001B5\bB\u0012\b\u0010\u0002\u001a\u0004\u0018\u00010\u0003\u0012\b\u0010\u0004\u001a\u0004\u0018\u00010\u0005\u0012\f\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\u00030\u0007\u0012\b\u0010\b\u001a\u0004\u0018\u00010\u0003¢\u0006\u0004\b\t\u0010\nB\u001f\bV\u0012\f\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\u00030\u0007\u0012\u0006\u0010\b\u001a\u00020\u0003¢\u0006\u0004\b\t\u0010\u000bB\u0019\bV\u0012\u0006\u0010\f\u001a\u00020\u0003\u0012\u0006\u0010\b\u001a\u00020\u0003¢\u0006\u0004\b\t\u0010\rB+\bW\u0012\f\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\u00030\u0007\u0012\b\u0010\u0002\u001a\u0004\u0018\u00010\u0003\u0012\b\u0010\u0004\u001a\u0004\u0018\u00010\u0005¢\u0006\u0004\b\t\u0010\u000eB\u0011\bQ\u0012\u0006\u0010\f\u001a\u00020\u0003¢\u0006\u0004\b\t\u0010\u000fJ\u0017\u0010\u0014\u001a\u00020\u00002\u0006\u0010\u0015\u001a\u00020\u0003H\u0080\u0080\u0004¢\u0006\u0002\b\u0016R\u001b\u0010\u0006\u001a\b\u0012\u0004\u0012\u00020\u00030\u0007X\u0086\u0084\b¢\u0006\b\n\u0000\u001a\u0004\b\u0010\u0010\u0011R\u0017\u0010\b\u001a\u0004\u0018\u00010\u0003X\u0086\u0084\b¢\u0006\b\n\u0000\u001a\u0004\b\u0012\u0010\u0013¨\u0006\u0017"}, d2 = {"Lkotlinx/serialization/MissingFieldException;", "Lkotlinx/serialization/SerializationException;", "message", "", "cause", "", "missingFields", "", "serialName", "<init>", "(Ljava/lang/String;Ljava/lang/Throwable;Ljava/util/List;Ljava/lang/String;)V", "(Ljava/util/List;Ljava/lang/String;)V", "missingField", "(Ljava/lang/String;Ljava/lang/String;)V", "(Ljava/util/List;Ljava/lang/String;Ljava/lang/Throwable;)V", "(Ljava/lang/String;)V", "getMissingFields", "()Ljava/util/List;", "getSerialName", "()Ljava/lang/String;", "withNewMessageInternal", "newMessage", "withNewMessageInternal$kotlinx_serialization_core", "kotlinx-serialization-core"}, k = 1, mv = {2, 3, 0}, xi = 48)
@ExperimentalSerializationApi
public final class MissingFieldException extends SerializationException {
    private final List<String> missingFields;
    private final String serialName;

    /* JADX WARN: 'this' call moved to the top of the method (can break code semantics) */
    @Deprecated(level = DeprecationLevel.HIDDEN, message = "Constructor used by the serializers generated by plugins older than Kotlin 1.5")
    public /* synthetic */ MissingFieldException(String missingField) {
        this("Field '" + missingField + "' is required, but it was missing", null, CollectionsKt.listOf(missingField), null);
        Intrinsics.checkNotNullParameter(missingField, "missingField");
    }

    /* JADX WARN: 'this' call moved to the top of the method (can break code semantics) */
    public MissingFieldException(String missingField, String serialName) {
        this("Field '" + missingField + "' is required for type with serial name '" + serialName + "', but it was missing", null, CollectionsKt.listOf(missingField), serialName);
        Intrinsics.checkNotNullParameter(missingField, "missingField");
        Intrinsics.checkNotNullParameter(serialName, "serialName");
    }

    private MissingFieldException(String str, Throwable th, List<String> list, String str2) {
        super(str, th);
        this.missingFields = list;
        this.serialName = str2;
    }

    /* JADX WARN: 'this' call moved to the top of the method (can break code semantics) */
    public MissingFieldException(List<String> missingFields, String serialName) {
        this(missingFields.size() == 1 ? "Field '" + missingFields.get(0) + "' is required for type with serial name '" + serialName + "', but it was missing" : "Fields " + missingFields + " are required for type with serial name '" + serialName + "', but they were missing", null, missingFields, serialName);
        Intrinsics.checkNotNullParameter(missingFields, "missingFields");
        Intrinsics.checkNotNullParameter(serialName, "serialName");
    }

    /* JADX WARN: 'this' call moved to the top of the method (can break code semantics) */
    @Deprecated(level = DeprecationLevel.ERROR, message = "Use constructor which accepts serialName parameter", replaceWith = @ReplaceWith(expression = "MissingFieldException(missingFields, descriptor.serialName, message, cause)", imports = {}))
    public MissingFieldException(List<String> missingFields, String str, Throwable th) {
        this(str, th, missingFields, null);
        Intrinsics.checkNotNullParameter(missingFields, "missingFields");
    }

    public final List<String> getMissingFields() {
        return this.missingFields;
    }

    public final String getSerialName() {
        return this.serialName;
    }

    public final MissingFieldException withNewMessageInternal$kotlinx_serialization_core(String newMessage) {
        Intrinsics.checkNotNullParameter(newMessage, "newMessage");
        return new MissingFieldException(newMessage, this, this.missingFields, this.serialName);
    }
}
